JNU-econovation/EEOS-FE

FE/src/apis/instance.ts

close #10 
서버단에서 실행시, window 객체가 준비되기 전에 요청하여 window 객체가 없는 버그.
토큰을 가져오기 전 window 객체가 준비되었는지 확인하는 로직 추가
- 토큰을 가져오는 로직은 axios의 interceptors 에 존재
- window가 준비되었는지 확인하는 로직을 추가. window가 존재하면 토큰을 가져오도록 수정

fix:  localstorage값을 가져오지 못하는 버그 수정

---

FE/src/apis/program.ts
FE/src/components/programDetail/program/ProgramInfo.tsx
FE/src/constants/API.ts

#15 
api 테스트를 위한 버튼을 추가하였습니다. 
버튼의 위치는 행사 상세정보 페이지에 있으며, 클릭시 api 를 실행합니다. 
아직 이슈가 완료되지 않았습니다. 추가적인 pr 이 올라올 예정입니다.

feat: api 테스트를 위한 버튼 추가

---

FE/src/apis/program.ts
FE/src/components/programDetail/program/ProgramInfo.tsx
FE/src/constants/MESSAGE.ts
FE/src/hooks/query/useProgramQuery.ts
FE/src/utils/authWithStorage.ts

closed #15 
행사를 생성하면 슬랙에 공지 알림이 가도록 기능 추가
- 슬랙 알림 요청을 위한 api를 추가하였습니다.
- api의 순서가 중요한 요청이므로(계시글 요청 -> 슬랙 알림 요청) 하나의 queryFn에 두 가지 서버 요청을 합니다.

feat: 계시글 업로드시 슬랙 공지 알림 보내기

---

FE/src/components/common/MemberList.tsx

#9 
게스트모드에서 사용자의 참석 여부를 확인하지 못하도록 하는 정책에 맞추기 위하여, 사용자의 참석 리스트를 확인하지 못하도록 드래그를 방지하기 위해 user-select를 none으로 설정.

feat: detail페이지의 사용자 참석 리스트를 드래그하지 못하도록 수정 (MemberList.tsx)

---

FE/src/apis/dtos/program.dto.ts
FE/src/apis/program.ts
FE/src/app/(admin)/admin/detail/[programId]/page.tsx
FE/src/app/(guest)/guest/detail/[programId]/page.tsx
FE/src/app/(private)/(program)/detail/[programId]/page.tsx
FE/src/components/programDetail/program/ProgramAttendStatusManageSection.tsx
FE/src/components/programDetail/program/ProgramDetail.tsx
FE/src/components/programDetail/program/ProgramInfo.tsx
FE/src/constants/API.ts
FE/src/hooks/query/useProgramQuery.ts
FE/src/types/program.ts

closed #50 
admin 도메인에서 해당 프로그램의 상태를 변경할 수 있는 기능을 추가합니다. 
- 리팩토링
- 반복되어 사용되는 타입을 정의하였습니다. https://github.com/JNU-econovation/EEOS-FE/commit/fe1597590f64558719ca30d2fcd6eedc734ef67a
- 코드의 일관성을 위하여 props를 카멜케이스로 변환하였습니다. https://github.com/JNU-econovation/EEOS-FE/commit/c1b3c0c527331dea40bbbfa9172cfa7b3581ce14
- 기능
- 각 버튼 클릭시 해당 상태로 변경할 수 있도록 modify 함수를 실행합니다.
- 현재 출석 상태값은 기존에 프로그램 디테일 정보를 받아와 캐싱해둔 값과 useEffect를 이용한 동기화를 시켜줍니다

[FEAT] 프로그램 출석 상태 변경 구현

---

FE/src/components/programDetail/program/DashboardCompound/Board/Board.tsx
FE/src/hooks/query/useQuestion.ts

closed #53 
query문에 enabled 값을 사용하여 질문 계시판에서 초기 질문 요청에 teamId가 undefined인 경우 요청을 보내지 않도록 수정

[FIX] 질문 계시판에 질문 요청 api에 팀 id가 제대로 담기지 않던 버그 수정

---

FE/src/components/programDetail/program/DashboardCompound/Board/Board.tsx

closed #53 
가져온 질문 데이터가 없을 경우 ui를 추가합니다. 

feat: 가져온 질문 데이터가 없을 경우 ui 추가 (Board.tsx)

---

FE/src/components/programDetail/program/ProgramDetail.tsx
FE/src/hooks/query/usePresentations.ts
FE/src/utils/github.ts

closed #56 
기존의 하위호환성 및 에러 상황에 따른 유저 인식을 위하여 url값이 null 인 경우 발표자료 섹션을 보여주지 않도록 변경

[FIX] 깃허브 url이 null 값인 경우 프론트단에서 발표자료를 보여주지 않도록 변경

---

FE/src/apis/dtos/program.dto.ts
FE/src/apis/program.ts
FE/src/components/main/ProgramListItem.tsx
FE/src/components/programDetail/program/ProgramAttendStatusManageSection.tsx
FE/src/types/program.ts

closed #59 
명세서가 변경됨에 따라서 attend_mode에서 attendMode로 변경
모든 api의 키는 카멜 케이스로 통일

fix: 명세서 변경에 따른 api 의 attend_mode 이름을 attendMode로 변경

---

FE/src/apis/member.ts

closed #64 
회원 활동 상태 변경 body 값이 제대로 담기지 않는 버그 수정
- body에 한번 더 {} 로 래핑하던 부분 제거

[FIX] 회원 활동 상태 변경 body 값이 제대로 담기지 않는 버그 수정

---

FE/src/components/programDetail/program/ProgramAttendStatusManageSection.tsx
FE/src/types/program.ts

closed #70 
기존에 종료 버튼 클릭시 non_open 값이 들어가 에러가 나던 코드를 올바르게 end 값이 들어가도록 수정
- ProgramAttendStatus 의 타입을 attend | late | non_open | end; 로 end를 추가

[FIX] 프로그램 출석 종료하기 버튼 클릭시 올바른 쿼리 스트링이 담기도록 수정

---

FE/src/hooks/query/useQuestionQuery.ts

closed #52 
기존 !!programId  && (!!teamId || teamId === 0) 로 enable이 되어있어서 programId가 0인 경우 요청을 하지 못하던 버그
(!!programId || programId === 0) && (!!teamId || teamId === 0)로 수정하여 0일떄에도 올바르게 요청할 수 있도록 변경

[FIX] 프로그램 아이디가 0인 경우 올바르게 요청을 보내지 못하던 버그 수정

---

.github/hooks/prepare-commit-msg.sample

#112 
커밋 메세지 푸터에 관련 이슈 번호를 자동으로 추가하는 스크립트 입니다. 
사용 방법은 아래와 같습니다.
1. 프로젝트의 루트 디렉토리에서 hooks 디렉토리 안의 prepare-commit-msg.sample 파일을 .git/hooks/prepare-commit-msg로 복사합니다
```bash
cp hooks/prepare-commit-msg.sample .git/hooks/prepare-commit-msg
```
2. 스크립트에 실행 권한을 부여합니다
```bash
chmod +x .git/hooks/prepare-commit-msg
```

chore: 관련 이슈 추가 자동화 스크립트 작성

---

FE/src/apis/program.ts
FE/src/components/programEdit/EditForm.tsx
FE/src/hooks/query/useProgramQuery.ts

#115 
기존에 수정하기시 githubUrl이 담기지 않던 버그가 존재하였습니다. 
request body에 해당 값이 담기지 않았다는 것을 확인하였고 추가해주었습니다!

[FIX] 수정하기 페이지에서 수정하기시 githubUrl이 담기지 않았던 버그 수정

---

FE/src/components/programDetail/program/ProgramHeader.tsx
FE/src/components/programEdit/ParticipantStateSection.tsx

closed #117 
출석체크가 진행 중인 상황에서, 멤버들의 출석 상태 변경 불가능하게 수정하였습니다.
출석체크를 진행하는지에 대한 확인을 위하여 해당 프로그램의 정보를 가져오는 로직이 추가되었습니다

[FIX] 출석체크가 진행 중인 상황에서, 멤버들의 출석 상태 변경 불가능하게 구현

---

FE/src/components/common/form/program/CreateForm.tsx
FE/src/components/programEdit/EditForm.tsx
FE/src/utils/convert.ts

closed #126 
프론트와 백엔드 모두 github url에 대하여 validation을 진행함
학기가 지나면서 기존의 validate와 맞지 않는 브랜치를 생성하게 될 수 있음. 이때 코드 변경의 비용을 줄이기 위하여 프론트에서는 해당 값에 대한 validation을 하지 않도록 함
github url의 validation로직을 주석처리

[CHORE] github url의 validation을 전부 백엔드로 위임

---

FE/src/hooks/query/useMemberQuery.ts

#130
- EEOS 주간발표에서 DetailPage의 참석, 지각, 불참, 미응답이 바로바로 반영되지 않는 이슈를 해결하였습니다.
1. 실시간으로 데이터를 받아오는 방법
- WebSocket을 열면 되는거 아닌가?
- 실시간 통신을 위해 기능 개발에 리소스 투자가 쉽지 않은 상황
1. 프론트에서 해결하자
- setInterval과 같은 기능으로 몇 초마다 요청을 받으면, 실시간처럼 보이게 할 수 있음
- 해당 부분을 쉽게 해주는 기능이 react-query의 refetchInterval
- 리액트에서 일정 간격으로 api를 호출하도록 하는 것
```
refetchInterval: number | false | ((data: TData | undefined, query: Query) => number | false)
Optional
If set to a number, all queries will continuously refetch at this frequency in milliseconds
If set to a function, the function will be executed with the latest data and query to compute a frequency
```
```tsx
export const useGetProgramMembersByAttend = ({
programId,
status,
}: GetProgramMemebersByAttend) => {
return useQuery({
queryKey: [API.MEMBER.ATTEND_STATUS(programId), …
```

[FEAT] member 상태에 따라 polling 적용

---

FE/src/hooks/query/useProgramQuery.ts

pollingm은 적용되었으나, admin에서 지각으로 변경해도 계속 polling이
받아와짐, 새로고침을 하면 더이상 polling이 되지 않으나 새로고침을 하지
않는 경우 주간발표가 끝날때까지 2초마다 요청 발생. 이를 해결하기 위해
useGetProgramId 의 staleTime을 5분에서 1분으로 변경

[FEAT] useGetProgramId staleTime 변경

---

FE/src/hooks/query/useProgramQuery.ts

멤버 상태의 polling에 대한 동시성 이슈를 해결하였습니다. cancelQueries를 통해 실행중이던 useGetProgramMembersByAttend 쿼리를 최초에 취소를 하여 동시성을 해결합니다.

[FEAT] 멤버 상태 polling synchronicity race condition 

---

FE/src/components/feature/detail/Dashboard/components/ChatList.tsx
FE/src/components/feature/detail/Dashboard/components/ReplyChat.tsx
FE/src/hooks/query/useQuestionQuery.ts
FE/src/utils/question.ts

closed #146 
대댓글의 대댓글 기능을 추가하였습니다. 
사실 댓글과 대댓글은 같은 컴포넌트를 사용하고 있어서 showReplyButton props 하나만 값을 true로 변경해서 간단히 구현할 수 있었습니다. 
추가적으로 해당 기능이 생김에 따라서 기존에 낙관적 업데이트를 하던 부분이, 대댓글의 대댓글을 달았을 때에도 올바르게 적용되도록 util함수를 수정하였습니다

[FEAT] 대댓글의 대댓글 기능 추가

---

FE/src/components/feature/detail/userAttendModal/UserAttendModal.tsx
FE/src/constants/ATTEND_STATUS.ts
FE/src/utils/__test__/program.test.ts
FE/src/utils/program.ts

#154 
closed #154 
기존에 아직 출석이 가능한 상태도 아님에도 불구하고 출석하기 버튼이 활성화 되는 버그가 존재하였습니다 
이에 올바르게 해당 로직을 수정하였습니다

[FIX] 올바르게 출석 상태에 따라서 출석 버튼이 활성화 되지 않던 버그 수정

---

FE/src/apis/auth.ts
FE/src/apis/instance.ts
FE/src/app/(admin)/layout.tsx
FE/src/app/(auth)/layout.tsx
FE/src/app/(private)/layout.tsx
FE/src/components/common/validate/Auth.tsx
FE/src/components/feature/detail/Dashboard/components/DashboardInput.tsx
FE/src/constants/ERROR_CODE.ts
FE/src/constants/ERROR_MESSAGE.ts
FE/src/hooks/useAuth.tsx

#21 
closed #21 
기존에는 로그인 여부에 따라 리다이렉트 로직이 존재하여도, 빌드타임에 정적으로 만들어진 html을 다운 받고, js가 렌더링되기 전까지의 시간동안 확인을 하면 안되는 화면을 사용자가 보게되는 문제가 존재함.
이는 기존에 layout.tsx에 토큰검사를 하는 컴포넌트를 하나 만들어 두어 로그인 여부에 따라서 접근을 막고 리다이렉트를 시키는 방식으로 구현되어있었음.
```
// layout.tsx
const PrivateLayout = ({ children }: PropsWithChildren) => {
return (
<>
{/* AuthValidate가 로그인 여부에 따른 리다이렉트를 수행하는 컴포넌트 */}
<AuthValidate />
<Header />
<main className="my-16 w-full px-3 sm:max-w-[800px] lg:max-w-[1112px]">
{children}
</main>
</>
);
};
export default PrivateLayout;
```
```
// AuthValidate.tsx
"use client";
import { useRouter } from "next/navigation";
import ROUTES from "@/constants/ROUTES";
import useAuth from "@/hooks/useAuth";
interface AuthValidateProps {
isHaveToLoggedInRoute?: boolean;
}
const AuthValidate = ({ isHaveToLoggedInRoute …
```

[FIX] 로그인과 리다이렉트 수정	

---

FE/src/apis/instance.ts

#21 
closed #21 
리프레시 토큰이 만료되면 reissue 응답에서 주는 에러 코드에 대한 핸들링 추가
토큰 만료시
- 가지고 있는 모든 토큰을 제거
- 에러 상황을 토스트메시지로 보여줌
- 로그인 페이지로 리다이렉트

[FIX] 리프레시토큰이 만료되었을 때 에러 처리 추가

---

FE/src/components/feature/login/default/SlackLoginBtn.tsx
FE/src/hooks/query/useAuthQuery.ts

closed #169 
기존에 로그인을 했었던 사용자라면 로그인 중 slack 페이지에서 권한 요청 절차를 하지 않도록 OAuth 요청 url의 propt값을 none으로 수정
해당 값이 올바르게 적용되는지에 대한 여부를 개발용에서 확인 후 해당 이슈를 닫도록 하겠습니다.

[CHORE] 로그인 플로우 변경에 따른 Slack OAuth 요청 url 수정

---

FE/src/hooks/query/useMemberQuery.ts

https://github.com/JNU-econovation/EEOS-FE/pull/180
→ 해당 pr에서 queryFn에 쿼리 값을 추가하며 발생한 문제
- startDate 또는 endDate가 undefined인 경우 요청을 보내지 않으며 이전 데이터가 사라짐
- attendanceSummary 값이 undefined가 되며 Loading... 문구 노출

feat: staleTime, keepPreviousData 옵션 추가

---

FE/src/components/feature/detail/Dashboard/TeamsTab.tsx
FE/src/hooks/query/usePresentations.ts
FE/src/hooks/query/useProgramQuery.ts

#186
closed #186 
기존에 guest요청과 admin 요청이 동일한 key로 캐싱이 되어 한 페이지 내에서 각각의 요청이 동시에 요청시 이후에 온 응답값을 사용하게 되던 문제가 존재하였습니다. 
각각의 요청을 다른 key로 캐싱하도록 하여 해결하였습니다

[FIX] 기존에 guest요청과 admin 요청이 동일한 key로 캐싱이 되어 올바르게 edit 권한을 확인하지 못하는 버그 수정

---

FE/src/components/feature/detail/Dashboard/TeamsTab.tsx

질문게시판에서 팀과 링크가 올바르게 매핑되지 않던 버그를 수정하였습니다.
원인 :
기존에 인자의 중복된 식별자를 사용함에 따라서 올바른 식별자가 참조되지 않는 휴먼 에러가 발생하였습니다. 
수정 :
식별자 이름을 다르게 사용하도록 수정하였습니다.

[HOTFIX] 질문게시판에서 팀과 링크가 올바르게 매핑되지 않던 버그 수정
