JNU-econovation/EEOS-FE

FE/src/app/(auth)/layout.tsx
FE/src/app/(private)/(program)/layout.tsx
FE/src/app/(private)/layout.tsx
FE/src/app/(private)/team-building/detail/page.tsx
FE/src/app/(private)/team-building/layout.tsx
FE/src/app/(private)/team-building/result/error.tsx
FE/src/app/layout.tsx
FE/src/components/common/Dropup.tsx
FE/src/components/common/ErrorFallback.tsx
FE/src/components/common/ErrorFallbackNoIcon.tsx
FE/src/components/common/form/program/ProgramForm.tsx
FE/src/components/common/form/teamBuilding/TeamBuildingForm.tsx
FE/src/components/common/memberTable/MemberTable.tsx
FE/src/components/login/RightSection.tsx
FE/src/components/programDetail/userAttendModal/UserAttendModal.tsx
FE/src/components/programEdit/EditMemberTableItem.tsx
FE/src/components/teamBuildingDetail/userInputModal/SentenceForm.tsx
FE/src/hooks/query/useAuthQuery.ts
FE/src/hooks/query/useTeamBuildingQuery.ts
FE/src/hooks/query/useUserQuery.ts
FE/src/utils/convert.ts
FE/src/utils/provider.tsx

style: eslint 규칙에 맞춰 코드 스타일 수정

---

FE/src/app/(auth)/login/logging-in/page.tsx

Hotfix: 로그인 code 테스트

---

FE/src/app/(auth)/login/logging-in/page.tsx
FE/src/utils/provider.tsx

fix: mutate 재요청 false 설정 & 로그인 기능 복원

---

FE/src/app/(auth)/login/logging-in/page.tsx

fix: 버튼 클릭 시 로그인 요청

---

FE/src/app/(auth)/login/logging-in/page.tsx

fix: 로그인 버튼 제거

---

FE/src/app/page.tsx

closed #18 
- 로그인 상태에서 /login 페이지로 가지 않던 버그 수정
현재 클라이언트단에서 리다이렉트를 처리중이고, 추가적으로 컴포넌트에서 처리를 하기 때문에 보안적으로, 성능적으로 좋지 않음. 개선이 필요

fix: 로그인 상태에서 /login 페이지로 가지 않던 버그 수정

---

FE/package.json
FE/pnpm-lock.yaml
FE/src/app/layout.tsx

closed #27 
EEOS 성능 확인을 위한 Speed Insights 추가하였습니다.
아래와 같은 성능을 확인할 수 있습니다. 
- Real Experience Score
- 나라별, Route/path별 성능 지표 확인

[FEAT] Speed Insights 추가

---

FE/src/apis/user.ts
FE/src/components/programDetail/userAttendModal/UserAttendModal.tsx
FE/src/constants/ATTEND_STATUS.ts
FE/src/hooks/query/useUserQuery.ts

closed #44 
- detail 페이지에서 출석하기 기능을 구현하였습니다. 
- 기존 출석 상태를 변경하는 방식에서 출석하기 버튼으로 변경됨에 따라서 보여지는 메시지를 변경하였습니다.

[FEAT] 출석체크 하기 기능 구현

---

FE/src/components/programDetail/program/DashboardCompound/Board/Board.tsx
FE/src/components/programDetail/program/DashboardCompound/Board/Chat.tsx
FE/src/components/programDetail/program/DashboardCompound/Board/ReplyChat.tsx
FE/src/components/programDetail/program/DashboardCompound/Board/common/ChatList.tsx
FE/src/components/programDetail/program/ProgramDashboard.tsx
FE/src/components/programDetail/program/ProgramDetail.tsx
FE/src/components/programDetail/program/ProgramInfo.tsx

closed #47 
- guest 모드에서 질문 작성 및 수정/삭제 기능을 제한합니다. 
- 이는 기존에 각 도메인별 page.tsx를 두었으므로, access에 대한 값을 props로 전달하여 분기하도록 구현

[FIX] guest mode에서 질문 작성 및 수정/삭제 기능 제한

---

FE/src/app/(admin)/admin/detail/[programId]/page.tsx
FE/src/app/(admin)/admin/edit/[programId]/page.tsx
FE/src/components/programDetail/program/DashboardCompound/Board/Board.tsx
FE/src/components/programDetail/program/DashboardCompound/Board/Chat.tsx
FE/src/components/programDetail/program/DashboardCompound/Board/ReplyChat.tsx
FE/src/components/programDetail/program/DashboardCompound/Board/common/ChatList.tsx
FE/src/components/programDetail/program/DashboardCompound/DashboardWrapper.tsx
FE/src/components/programDetail/program/DashboardCompound/Form.tsx
FE/src/components/programDetail/program/ProgramDashboard.tsx
FE/src/components/programDetail/program/ProgramDetail.tsx

closed #61 
admin 도메인에서 detail의 기능을, 기능 명세서에 맞추어 수정하였습니다. 수정 내용은 아래와 같습니다. 
- admin 도메인의 하단바 제거
- 질문 남길 수 없도록 수정

[FIX] admin 도메인 detail 페이지 수정

---

FE/src/hooks/query/useMemberQuery.ts

closed #52 
유저 활동 정보 수정에 낙관적 업데이트 적용
이는 전체 유저 정보만 업데이트 하며, 나머지 상태는 서버와 동기화를 위하여 캐싱을 삭제하는 방식으로 구현

[REFACTOR] 유저 활동 정보 수정 낙관적 업데이트 적용

---

FE/src/constants/API.ts

closed #52
명세서의 요구사항이 변경됨에 따라서 member의 활동상태변경 url을 변경합니다.

[CHORE] 명세서 요구사항 변경에 따라 url 주소 변경

---

FE/src/constants/API.ts

[FIX] 명세서의 요구사항이 변경됨에 따라서 member의 활동상태변경 url 변경

---

FE/src/components/common/form/program/CreateForm.tsx
FE/src/components/programDetail/userAttendModal/UserAttendModal.tsx

closed #76 
- /create 에서 제출시 validation 로직에서 githubUrl값이 없던 부분에 추가

[FIX] githubUrl 입력 여부를 확인합니다. 

---

FE/src/components/common/header/Modal/UserActiveModal.tsx
FE/src/components/common/header/Modal/UserInfoSection.tsx

[FIX] 유저가 본인의 활동 상태를 변경하지 못하도록 수정

---

FE/src/components/main/Program.tsx
FE/src/components/main/ProgramListItem.tsx

closed #80 
올바르게 출석 진행중이 표시되지 않던 버그 수정"

[FIX] 올바르게 출석 진행중이 표시되지 않던 버그 수정

---

FE/src/components/common/form/program/CreateCategory.tsx
FE/src/components/common/form/program/ProgramTitle.tsx
FE/src/components/main/Program.compound.tsx
FE/src/utils/test.ts

closed #82 
[FIX]  명세서대로 /create에서 수요조사 및 카테고리 변경 불가능 하도록 수정

[FIX]  명세서대로 /create에서 수요조사 및 카테고리 변경 불가능 하도록 수정

---

FE/src/components/programDetail/program/DashboardCompound/DashboardWrapper.tsx
FE/src/components/programDetail/program/ProgramAttendStatusManageSection.tsx
FE/src/components/programDetail/program/ProgramPresentations.tsx

closed #83 
[FIX] 명확히 프로그램의 출석 상태값이 변경되면 보이도록 수정

[FIX] 명확히 프로그램의 출석 상태값이 변경되면 보이도록 수정

---

FE/src/components/programDetail/program/ProgramAttendStatusManageSection.tsx

closed #83
프로그램 종료시 상태 변경 요청을 보내지 못하도록 수정

[FIX] 프로그램 종료시 상태 변경 요청을 보내지 못하도록 수정

---

FE/src/components/common/form/program/CreateForm.tsx
FE/src/hooks/query/useProgramQuery.ts

closed #81 
[FEAT] 프론트단에서 깃허브 링크에 대한 유효성 검사 추가

[FEAT] 프론트단에서 깃허브 링크에 대한 유효성 검사 추가

---

FE/src/components/programDetail/program/DashboardCompound/Board/ReplyChat.tsx
FE/src/components/programDetail/program/DashboardCompound/Board/common/ChatList.tsx

closed #75 
[FIX] 답글에는 답변할 수 없도록 수정

[FIX] 답글에는 답변할 수 없도록 수정

---

FE/src/components/common/form/program/CreateForm.tsx
FE/src/components/programEdit/EditForm.tsx
FE/src/hooks/useProgramFormData.ts
FE/src/utils/github.ts

closed #96 
수정하기 페이지에서 깃허브 주소가 초기에 표시되지 않는 버그 수정

[FIX] 수정하기 페이지에서 깃허브 주소가 초기에 표시되지 않는 버그 수정

---

FE/src/components/programDetail/program/EditAndDeleteButton.tsx
FE/src/components/programEdit/EditForm.tsx

closed #104 
기존에 행사 삭제시 /admin 이 아닌 기존 도매인으로 리다이렉트 되던 버그 수정

[FIX] 행사 삭제시 올바르게 리다이렉트 되지 않던 버그 수정

---

FE/package.json
FE/pnpm-lock.yaml
FE/src/app/layout.tsx

closed #109 
- next/third-parties 의존성 추가
- Google Analytics 적용

[FEAT] Google Analytics 적용

---

FE/src/utils/github.ts

github url validation pattern이 이번 학기에 team case변경에 따른 pattern 수정

[HOTFIX] github url validation pattern 수정

---

FE/src/components/common/form/program/CreateForm.tsx
FE/src/components/programEdit/EditForm.tsx
FE/src/utils/convert.ts
FE/src/utils/github.ts

우선적으로 프론트에서 github url에 대한  validation 하지 않도록 수정하였습니다.
이는 백엔드와 추후에 논의해본 후 정책을 확입해야합니다.

[HOTFIX]우선적으로 프론트에서 github url에 대한  validation 하지 않도록 수정

---

FE/src/components/programDetail/userAttendModal/AttendStatusView.tsx
FE/src/components/programDetail/userAttendModal/UserAttendModal.tsx
FE/src/hooks/query/useProgramQuery.ts

closed #124 
조건문이 올바르게 되어있지 않아 당일날 출석중이지 않는 상태에서 출석하기 버튼이 활성화 되어있던 버그 수정

[FIX] 올바르게 출석체크 버튼이 활성화 되도록 수정

---

FE/src/apis/__test__/program.test.ts

closed #128 
도메인 이전에 따른 테스트 코드를 변경하였습니다

test: 슬랙 메시지 요청 테스트 url 수정

---

FE/src/hooks/query/useMemberQuery.ts

[FEAT] attendStatus에 따른 refetchInterval을 통한 polling 구현

---

FE/src/components/common/CheckBox/CheckBox.tsx
FE/src/components/feature/detail/Dashboard/components/DashboardInput.tsx

closed #144 
질문 입력 창의 크기를 조절할 수 있도록 수정하였습니니다!
기존에 resize-none으로 설정되어있던 부분을 제거하였습니다

[FEAT] 질문 입력 창 크기 조절 추가

---

FE/src/hooks/query/useProgramQuery.ts

refetchInterval로 해결하였습니다. 자세한 내용은 pr에 작성합니다.

[FIX] polling issue 해결

---

FE/src/hooks/query/useProgramQuery.ts

[FIX] onSuccess invalidateQueries 로직 추가

---

FE/src/hooks/query/useProgramQuery.ts

[FIX] attendMode invalidateQueries 적용

---

FE/src/components/feature/detail/Dashboard/components/DashboardInput.tsx

[HOTFIX] 익명 댓글 기능 임시적으로 동작하지 않도록 수정

---

FE/src/components/feature/detail/Dashboard/components/DashboardInput.tsx

기존에 서버 배포 이슈로 인해 핫픽스로 막아두었던 익명 체크박스를 다시 사용 가능하도록 수정했습니다
기존에 서버 배포 이슈로 인해 핫픽스로 막아두었던 익명 체크박스를 다시 사용 가능하도록 수정했습니다!

[HOTFIX] 기존에 막아두었던 익명 체크박스를 사용 가능하도록 수정

---

FE/src/apis/instance.ts

#21
closed #21
기존에는 resonse에서만 reissue요청시 토큰 제거하고 알림을 보내고 로그인 페이지로 이동시키도록 추가했었는데, 
이를 다른 요청 시에도 동일하게 동작하도록 수정

[FIX] reissue를 요청하는 모든 상황에 동일하게 토큰을 제거하고 알림을 보내고 로그인 페이지로 이동시키도록 추가

---

FE/src/apis/dtos/member.dto.ts
FE/src/apis/dtos/program.dto.ts
FE/src/apis/member.ts
FE/src/app/(private)/mypage/page.tsx
FE/src/components/common/header/HeaderNavSection.tsx
FE/src/components/common/header/LogoutButton.tsx
FE/src/components/common/header/UserBtn.tsx
FE/src/components/mypage/AttendanceBadge.tsx
FE/src/components/mypage/AttendanceOverviewSection.tsx
FE/src/components/mypage/AttendanceTable.tsx
FE/src/components/mypage/DateSelector.tsx
FE/src/components/mypage/UserInfoSection.tsx
FE/src/constants/API.ts
FE/src/hooks/query/useMemberQuery.ts
FE/src/hooks/query/useUserQuery.ts
FE/src/types/member.ts

마이페이지를 구현합니다.
- 마이페이지에서만 사용되는 에셋들은 svg 태그로 추가하였습니다.
- 추가로 행사 리스트 조회 응답값 수정 사항을 적용하였습니다. [관련 스레드](https://econo-black-company.slack.com/archives/C064W4ZGD7F/p1742181300539029)
마이페이지 전체 UI
날짜 선택 기능

마이페이지 기능을 구현합니다.

---

FE/src/components/feature/detail/userAttendModal/UserAttendModal.tsx
FE/src/components/feature/detail/userAttendModal/UserAttendModalSection.tsx
FE/src/hooks/query/useMemberQuery.ts
FE/src/hooks/query/useUserQuery.ts

#173
closed #173 
출석체크시 파이어 핑거의 쿼리를 invalidate합니다

[FEAT] 출석체크시 파이어핑거 쿼리를 invalidate하도록 수정

---

FE/src/components/mypage/AttendanceTable.tsx
FE/src/hooks/query/useMemberQuery.ts

- `출석하러 가기` 클릭 시 연관없는 행사 상세 페이지로 이동하는 문제를 해결합니다.
- 하드코딩 된 programId 값을 제거합니다.
- 날짜 변경 시 리스트가 바로 갱신되지 않는 문제를 해결합니다.
- queryKey에 요청 파라미터 값을 추가합니다.

[FIX] 마이페이지 오류 수정

---

FE/src/components/feature/detail/Dashboard/components/DashboardInput.tsx

closed #181 
기존에 엔터키를 눌러서 질문 제출하는 기능을 롤백합니다

[FIX] 엔터키를 눌러서 제출하는 기능 롤백

---

FE/src/components/feature/detail/program/EditAndDeleteButton.tsx
FE/src/components/feature/detail/program/ProgramHeaderSection.tsx

기존에 행사 제거시 올바르게 programId값이 들어가지 않아 제거되지 않던 버그 수정

[HOTFIX] 행사 제거시 올바르게 제거되지 않던 버그 수정

---

FE/src/apis/instance.ts

reissue가 되지 않을 떄 강제로 로그아웃을 시키는 로직을 추가하였습니다.

[HOTFIX] reissue가 되지 않을 때 강제로 로그아웃 시키는 로직 추가

---

FE/public/icons/caret_down.svg
FE/public/icons/caret_up.svg
FE/src/apis/dtos/member.dto.ts
FE/src/apis/member.ts
FE/src/components/common/Selector/Selector.tsx
FE/src/components/common/Table/TableCompounds/MemberManageList.tsx
FE/src/components/common/toggle/ActiveStatusToggle.tsx
FE/src/constants/API.ts
FE/src/constants/DEPARTMENT.ts
FE/src/hooks/query/useMemberQuery.ts
FE/src/types/member.ts

closed #196 
회원 관리 페이지에서 회원의 부서를 변경할 수 있도록 기능을 구현하였습니다.

[FEAT] 회원 관리 페이지에서 회원의 부서를 변경할 수 있도록 기능 구현

---

FE/src/components/feature/floating/EventCalender.tsx

closed #194
fix: etx를 ect로 잘못 작성된 오타를 수정하였습니다.

[fix] etx를 ect로 잘못 작성된 오타 수정

---

FE/src/components/feature/floating/EventCalender.tsx

#194
작은 캘린더에서 자세히 보기를 눌렀을 때 캘린더가 접히도록 기능 추가

[FEAT] 작은 캘린더에서 자세히 보기를 눌렀을 때 캘린더가 접히도록 기능 추가

---

FE/src/components/calendar/CalendarDay.tsx
FE/src/components/calendar/EventInfoModal.tsx
FE/src/components/feature/floating/EventCalender.tsx
FE/src/constants/COLOR.ts

FIX: 색상 상수 관련 코드 롤백 후 색상만 변경

---

FE/src/components/calendar/CalendarDay.tsx
FE/src/components/calendar/CreateEventModal.tsx
FE/src/components/calendar/EventInfoModal.tsx
FE/src/components/common/header/CalendarBtn.tsx

[FEAT] 큰 캘린더의 색을 작은 캘린더와 통일
